export { default as LoginScreen } from './LoginScreen/LoginScreen'
export { default as HomeScreen } from './HomeScreen/HomeScreen'
export { default as RegistrationScreen } from './RegistrationScreen/RegistrationScreen'
export { default as StudentRegistrationScreen } from './StudentRegistrationScreen/StudentRegistrationScreen'
export { default as StudentInfoScreen } from './StudentInfoScreen/StudentInfoScreen'
export { default as TeacherInfoScreen } from './TeacherInfoScreen/TeacherInfoScreen'
export { default as TeacherDetailsScreen } from './TeacherDetialsScreen/TeacherDetailsScreen'
export { default as StudentPerformanceScreen } from './StudentPerformanceScreen/StudentPerformanceScreen'